### ISSUE TITLE
Failed to import "checkname"

### ISSUE THREAD

**Issue by tobyL0** [07031218/emby_bot#1]
报错如图：
![image](https://github.com/07031218/emby_bot/assets/62921013/4a675d78-6bea-4230-a24d-ac33ed2d65d5)
 
已按要求配置以及安装requirement，但是运行报错

**Comment by 07031218** [comment]
> 报错如图： ![image](https://user-images.githubusercontent.com/62921013/243151907-4a675d78-6bea-4230-a24d-ac33ed2d65d5.png)
> 
> 已按要求配置以及安装requirement，但是运行报错

```shell
pip3 install websocket-client
``` 
缺少依赖，安装下依赖。
